version: '3.8'

services:

  downtime:
    image: "${DOCKER_REGISTRY:-my.registry}/eq:${IMAGE_TAG:-local}"
    build:
      context: ./
      dockerfile: Dockerfile.application
    environment:
      - CONFIG_PATH=/
      - LOCALSTACK_ENDPOINT=http://localstack:4566
      - LOCALSTACK=true
    volumes:
      - ./:/debug
    networks:
      - localstack

  builder:
    image: "golang:1.20-buster"
    environment:
      - CGO_ENABLED=0
      - GO_ARGS=${GO_ARGS}
      - GOBIN=/go/src/github.com/brimb0r/application
      - GOCACHE=/go/src/github.com/brimb0r/application/.cache
      - GIT_COMMIT="${GIT_COMMIT:-local}"
      - COMPONENT_TESTS=true
    volumes:
      - ./:/go/src/github.com/brimb0r/application
      - ./.mod:/go/pkg/mod
    command:
      - tail
      - -f
      - /dev/null
    working_dir: /go/src/github.com/brimb0r/application


networks:
  localstack:
    name: localstack
    external: true