services:

  localstack:
    ports:
      - "4566-4599:4566-4599"
      - "8080:8080"
  mongo-database:
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

  zookeeper:
    image: "bitnami/zookeeper:latest"
    expose:
      - "2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: "bitnami/kafka:latest"
    ports:
      - "7777:7777"
      - "27777:27777"
    depends_on:
      - zookeeper

  karapace-registry:
    ports:
      - "7878:7878"

networks:
  default:
    name: localstack

volumes:
  mongodata:
    name: mongodata
    external: true